import type { NextPage } from "next";
import { getSession } from "next-auth/react";
import Head from "next/head";
import { Field } from "../lib/Field";
import Navbar from "../lib/navbar";
import Points from "../lib/Points";
import { trpc } from "../utils/trpc";

export async function getServerSideProps(context) {
  const session = await getSession(context);
  if (!session) {
    return {
      redirect: {
        destination: "/",
        permanent: false,
      },
    };
  }
  const isAdmin = await prisma?.user.findUnique({
    where: {
      id: session?.user?.id,
    },
    select: {
      role: true,
    },
  });

  if (isAdmin?.role !== "admin") {
    return {
      redirect: {
        destination: "/",
        permanent: false,
      },
    };
  }

  return {
    props: {},
  };
}
const Admin: NextPage = () => {
  return (
    <>
      <Navbar />
      <Head>
        <title>Seven vs. Wild Bingo</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen bg-gradient-to-b from-black to-slate-900"></main>
    </>
  );
};

export default Admin;
