import type { GetServerSideProps, NextPage } from "next";
import { getSession } from "next-auth/react";
import Head from "next/head";
import Board from "../lib/Board";
import { CreateBoard } from "../lib/createBoard";
import Navbar from "../lib/navbar";
import { prisma } from "../server/db/client";

interface BingoPageProps {
  count: number | undefined;
}
export const getServerSideProps: GetServerSideProps<BingoPageProps> = async (
  context
) => {
  const session = await getSession(context);
  if (!session) {
    return {
      redirect: {
        destination: "api/auth/signin",
        permanent: false,
      },
    };
  }
  let count = await prisma.bingoEntry.count({
    where: {
      userId: session?.user?.id,
    },
  });

  //reset board for undefined state
  if (count !== 0 && count !== 25) {
    await prisma.bingoEntry.deleteMany({
      where: {
        userId: session?.user?.id,
      },
    });
    count = 0;
  }

  return {
    props: {
      count: count,
    },
  };
};
const Bingo: NextPage<BingoPageProps> = ({ count }) => {
  const getState = () => {
    if (count === 0) {
      return <CreateBoard />;
    } else if (count === 25) {
      return <Board />;
    } else {
      return <>Empty Board</>;
    }
  };

  return (
    <>
      <Navbar />
      <Head>
        <title>Seven vs. Wild Bingo</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen bg-gradient-to-b from-black to-slate-900">
        {getState()}
      </main>
    </>
  );
};

export default Bingo;
