import type { NextPage } from "next";
import Head from "next/head";
import Navbar from "../lib/navbar";
import Projections from "../lib/NewProjection";

const Home: NextPage = () => {

  return (
    <>
      <Navbar />
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen bg-gradient-to-b from-black to-slate-900 ">
        <div className="p-3">
          <Projections />
        </div>
      </main>
    </>
  );
};

export default Home;
