import type { NextPage } from "next";
import Head from "next/head";
import Navbar from "../lib/navbar";
import Projections from "../lib/NewProjection";
import { ProjectionList } from "../lib/ProjectionList";
import ScoreBoard from "../lib/ScoreBoard";

const Home: NextPage = () => {
  return (
    <>
      <Navbar />
      <Head>
        <title>Seven vs. Wild Bingo</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen bg-gradient-to-b from-black to-slate-900 ">
        <div className="py-8 px-4 mx-auto max-w-screen-xl text-center lg:py-10 lg:px-12">
          <h1 className="mb-4 text-4xl font-extrabold tracking-tight leading-none text-gray-900 md:text-5xl lg:text-6xl dark:text-white">
            Deine Ideen für das Seven vs. Wild Bingo
          </h1>
          <p className="mb-4 text-lg font-normal text-gray-500 lg:text-xl sm:px-16 xl:px-48 dark:text-gray-400">
            Füge hier deine Ideen für das Seven vs. Wild Bingo ein und erstelle
            dir eine eigene Bingo Karte für die zweite Staffel von Seven vs.
            Wild.
          </p>
        </div>
        <div className="p-3">
          <Projections />
        </div>
        <div className="py-8 px-4 mx-auto max-w-screen-xl text-center lg:py-10 lg:px-12">
          <h1 className="my-8 text-2xl font-extrabold tracking-tight leading-none text-gray-900 md:text-3xl lg:text-3xl dark:text-white">
            Aktuelle Bingo Karten
          </h1>
        </div>
        <div className="container mx-auto max-w-md">
          <ProjectionList />
          <ScoreBoard />
        </div>
        <div className="mt-96">{"."}</div>
      </main>
    </>
  );
};

export default Home;
